COUNT    | LINE
-----------------------------------------------------
      16 | (EVERYTHING I DO) I DO IT FOR YOU	BRYAN ADAMS
      14 | LOVE IS ALL AROUND	WET WET WET
      10 | I WILL ALWAYS LOVE YOU	WHITNEY HOUSTON
      10 | UMBRELLA	RIHANNA FEAT. JAY-Z
       9 | BOHEMIAN RHAPSODY	QUEEN
       9 | IT'S NOW OR NEVER	ELVIS PRESLEY
       9 | MULL OF KINTYRE/GIRLS' SCHOOL	WINGS
       9 | TWO TRIBES	FRANKIE GOES TO HOLLYWOOD
       9 | YOU'RE THE ONE THAT I WANT	JOHN TRAVOLTA AND OLIVIA NEWTON-JOHN
       8 | CRAZY	GNARLS BARKLEY
       8 | STAY	SHAKESPEARS SISTER
       8 | SUGAR, SUGAR	ARCHIES
       8 | WONDERFUL LAND	SHADOWS
       7 | (IS THIS THE WAY TO) AMARILLO	TONY CHRISTIE FEAT. PETER KAY
       7 | BELIEVE	CHER
       7 | BLEEDING LOVE	LEONA LEWIS
       7 | CATHY'S CLOWN	EVERLY BROTHERS
       7 | FROM ME TO YOU	BEATLES
       7 | GREEN GREEN GRASS OF HOME	TOM JONES
       7 | HELLO GOODBYE	BEATLES
       7 | I REMEMBER YOU	FRANK IFIELD
       7 | I'D DO ANYTHING FOR LOVE (BUT I WON'T DO THAT)	MEAT LOAF
       7 | IN THE SUMMERTIME	MUNGO JERRY
       7 | SUMMER NIGHTS	JOHN TRAVOLTA AND OLIVIA NEWTON-JOHN
       7 | THINK TWICE	CELINE DION
       7 | UNCHAINED MELODY/(THERE'LL BE BLUEBIRDS OVER) THE WHITE CLIFFS OF DOVER	ROBSON GREEN & JEROME FLYNN
       7 | WANNABE	SPICE GIRLS
       6 | A WHITER SHADE OF PALE	PROCOL HARUM
       6 | BAND OF GOLD	FREDA PAYNE
       6 | BRIGHT EYES	ART GARFUNKEL
       6 | BYE BYE BABY	BAY CITY ROLLERS
       6 | DANCING QUEEN	ABBA
       6 | DON'T GO BREAKING MY HEART	ELTON JOHN AND KIKI DEE
       6 | EARTH SONG	MICHAEL JACKSON
       6 | GET BACK	BEATLES
       6 | HELLO	LIONEL RICHIE
       6 | HOT LOVE	T. REX
       6 | I HEAR YOU KNOCKING	DAVE EDMUNDS' ROCKPILE
       6 | I JUST CALLED TO SAY I LOVE YOU	STEVIE WONDER
       6 | I'LL BE MISSING YOU	PUFF DADDY AND FAITH EVANS FEAT. 112
       6 | IT'S LIKE THAT	RUN-DMC VS JASON NEVINS
       6 | KARMA CHAMELEON	CULTURE CLUB
       6 | MY SWEET LORD	GEORGE HARRISON
       6 | RELEASE ME	ENGELBERT HUMPERDINCK
       6 | RHYTHM IS A DANCER	SNAP!
       6 | RIDE ON TIME	BLACK BOX
       6 | SAVE YOUR KISSES FOR ME	BROTHERHOOD OF MAN
       6 | SHE LOVES YOU	BEATLES
       6 | THE WONDER OF YOU	ELVIS PRESLEY
       6 | THE YOUNG ONES	CLIFF RICHARD AND THE SHADOWS
       6 | THOSE WERE THE DAYS	MARY HOPKIN
       6 | TWO LITTLE BOYS	ROLF HARRIS
       6 | WE FOUND LOVE	RIHANNA FT CALVIN HARRIS
       6 | WHERE IS THE LOVE?	BLACK EYED PEAS
       6 | WOODEN HEART	ELVIS PRESLEY
       5 | 19	PAUL HARDCASTLE
       5 | ABBA-ESQUE (EP)	ERASURE
       5 | AMAZING GRACE	ROYAL SCOTS DRAGOON GUARDS
       5 | ANOTHER BRICK IN THE WALL (PART II)	PINK FLOYD
       5 | APACHE	SHADOWS
       5 | BLOCKBUSTER!	SWEET
       5 | BLURRED LINES	ROBIN THICKE/TI/PHARRELL
       5 | BOHEMIAN RHAPSODY/THESE ARE THE DAYS OF OUR LIVES	QUEEN
       5 | CALL ON ME	ERIC PRYDZ
       5 | CHINA IN YOUR HAND	T'PAU
       5 | CHIRPY CHIRPY CHEEP CHEEP	MIDDLE OF THE ROAD
       5 | DAY TRIPPER/WE CAN WORK IT OUT	BEATLES
       5 | DISTANT DRUMS	JIM REEVES
       5 | DO THEY KNOW IT'S CHRISTMAS?	BAND AID
       5 | DON'T YOU WANT ME	HUMAN LEAGUE
       5 | GOOD LUCK CHARM	ELVIS PRESLEY
       5 | GRACE KELLY	MIKA
       5 | HIPS DON'T LIE	SHAKIRA FEAT. WYCLEF JEAN
       5 | HONKY TONK WOMEN	ROLLING STONES
       5 | I FEEL FINE	BEATLES
       5 | I KISSED A GIRL	KATY PERRY
       5 | I SHOULD BE SO LUCKY	KYLIE MINOGUE
       5 | I WANT TO HOLD YOUR HAND	BEATLES
       5 | KILLING ME SOFTLY	FUGEES
       5 | KNOCK THREE TIMES	DAWN
       5 | KNOWING ME, KNOWING YOU	ABBA
       5 | LONG HAIRED LOVER FROM LIVERPOOL	LITTLE JIMMY OSMOND
       5 | LOVE GROWS (WHERE MY ROSEMARY GOES)	EDISON LIGHTHOUSE
       5 | LOVESICK BLUES	FRANK IFIELD
       5 | MAGGIE MAY	ROD STEWART
       5 | MERCY	DUFFY
       5 | MERRY XMAS EVERYBODY	SLADE
       5 | NEVER GONNA GIVE YOU UP	RICK ASTLEY
       5 | NO LIMIT	2 UNLIMITED
       5 | NOW YOU'RE GONE	BASSHUNTER FEAT. DJ MENTAL THEO'S BAZZHEADZ
       5 | PLEASE DON'T GO/GAME BOY	KWS
       5 | PUPPY LOVE	DONNY OSMOND
       5 | RELAX	FRANKIE GOES TO HOLLYWOOD
       5 | RIVERS OF BABYLON	BONEY M
       5 | SACRIFICE/HEALING HANDS	ELTON JOHN
       5 | SOMEBODY THAT I USED TO KNOW	GOTYE FT KIMBRA
       5 | SOMEONE LIKE YOU	ADELE
       5 | SOMETHING ABOUT THE WAY YOU LOOK/CANDLE IN THE WIND '97	ELTON JOHN
       5 | SPACEMAN	BABYLON ZOO
       5 | STAND AND DELIVER	ADAM AND THE ANTS
       5 | STAY ANOTHER DAY	EAST 17
       5 | SWING THE MOOD	JIVE BUNNY AND THE MASTERMIXERS
       5 | TEARS	KEN DODD
       5 | TELSTAR	TORNADOS
       5 | THE LAST WALTZ	ENGELBERT HUMPERDINCK
       5 | THE ONE AND ONLY	CHESNEY HAWKES
       5 | THE ONLY WAY IS UP	YAZZ AND THE PLASTIC POPULATION
       5 | THE POWER OF LOVE	JENNIFER RUSH
       5 | THE SHOOP SHOOP SONG (IT'S IN HIS KISS)	CHER
       5 | THREE TIMES A LADY	COMMODORES
       5 | UPTOWN GIRL	BILLY JOEL
       5 | WAY DOWN	ELVIS PRESLEY
       5 | YOU'RE BEAUTIFUL	JAMES BLUNT
